/* GENERATED by tools/gen-registry.mjs from tools/cores.json — do not edit.
 * One CORE(name) per statically linked core; cores.c defines CORE twice (extern
 * prototypes, then vtable entries) and includes this file each time (X-macro). */
CORE(fceumm)
CORE(snes9x)
CORE(segaMD)
CORE(gambatte)
CORE(pce)
